const standardDeck = {
    Hearts:{
        2: "2 of Hearts",
        3: "3 of Hearts",
        4: "4 of Hearts",
        5: "5 of Hearts",
        6: "6 of Hearts",
        7: "7 of Hearts",
        8: "8 of Hearts",
        9: "9 of Hearts",
        10: "10 of Hearts",
        11: "Jack of Hearts",
        12: "Queen of Hearts",
        13: "King of Hearts",
        14: "Ace of Hearts",
    },
    Spades:{
        2: "2 of Spades",
        3: "3 of Spades",
        4: "4 of Spades",
        5: "5 of Spades",
        6: "6 of Spades",
        7: "7 of Spades",
        8: "8 of Spades",
        9: "9 of Spades",
        10: "10 of Spades",
        11: "Jack of Spades",
        12: "Queen of Spades",
        13: "King of Spades",
        14: "Ace of Spades"
    },
    Diamonds: {
        2: "2 of Diamonds",
        3: "3 of Diamonds",
        4: "4 of Diamonds",
        5: "5 of Diamonds",
        6: "6 of Diamonds",
        7: "7 of Diamonds",
        8: "8 of Diamonds",
        9: "9 of Diamonds",
        10: "10 of Diamonds",
        11: "Jack of Diamonds",
        12: "Queen of Diamonds",
        13: "King of Diamonds",
        14: "Ace of Diamonds",
    },
    Clubs: {
        2: "2 of Clubs",
        3: "3 of Clubs",
        4: "4 of Clubs",
        5: "5 of Clubs",
        6: "6 of Clubs",
        7: "7 of Clubs",
        8: "8 of Clubs",
        9: "9 of Clubs",
        10: "10 of Clubs",
        11: "Jack of Clubs",
        12: "Queen of Clubs",
        13: "King of Clubs",
        14: "Ace of Clubs",
      },

}

const deckOfDragons = {
    "High House Life": {
        1: "King",
        2: "Queen",
        3: "Champion",
        4: "Priest",
        5: "Herald",
        6: "Soldier",
        7: "Weaver",
        8: "Mason",
        9: "Virgin"
    },
    "High House Death": {
        1: "King",
        2: "Queen",
        3: "Knight",
        4: "Magi",
        5: "Herald",
        6: "Soldier",
        7: "Spinner",
        8: "Mason",
        9: "Virgin"
    },
    "High House Light": {
        1: "King",
        2: "Queen",
        3: "Champion",
        4: "Priest",
        5: "Captain",
        6: "Soldier",
        7: "Seamstress",
        8: "Builder",
        9: "Maiden"
    },
    "High House Dark": {
        1: "King",
        2: "Queen",
        3: "Knight",
        4: "Magi",
        5: "Herald",
        6: "Captain",
        7: "Soldier",
        8: "Weaver",
        9: "Mason",
        10: "Wife"
    },
    "High House Shadow": {
        1: "King",
        2: "Queen",
        3: "Assassin",
        4: "Magi",
        5: "Knight",
        6: "Hound",
        7: "Apprentice",
        8: "Mistress"
    },
    "High House Chains": {
        1: "Ruler",
        2: "Consort",
        3: "Reaver",
        4: "Knight",
        5: "The Seven of the Dead Fires",
        6: "Herald",
        7: "Magi",
        8: "Cripple",
        9: "Leper",
        10: "Fool"
    },
    "High House War": {
        1: "Lords of War", 
        2: "Hunter",
        3: "Guardians of the Road",
        4: "Guardians of the Dead", 
        5: "Mercenary",
        6: "Soldier",
        7: "Lifeslayer",
        8: "Deathslayer",
        9: "Herald"
    }
};

export {standardDeck, deckOfDragons};
